= Ångade vegodumplings med krämig het dippsås

https://www.koket.se/angade-vegodumplings-med-kramig-het-dippsas[Jennie Walldén]

4 portioner, ca 45 min.

Tips: äggröran i fyllningen kan bytas mot fast, smulad tofu.

== Ingredienser

=== Dumplings

|===
| 1   | förp   | gyozaplattor, tinade (à 300 g)
| 2   | st     | vitlöksklyftor, finhackade
| 3   | cm     | färsk ingefära, finhackad
| 300 | g      | champinjoner, finhackade
| 350 | g      | vitkål, finhackad
| 1   | st     | gul lök, finhackad
| 4   | st     | ägg
| 3   | msk    | japansk soja
| 1   | msk    | sesamolja
|===

=== Dippsås

|===
| 2   | dl     | majonnäs
| 2   | msk    | japansk soja
| 2   | tsk    | risvinäger
| 0,5 | msk    | strösocker
| 1-2 | msk    | sriracha
|===

=== Topping

|===
| 2   | st     | salladslökar, tunt skivade
| 1   | knippe | färsk koriander, grovt hackad
| 1   | msk    | rostade sesamfrön
|===

== Fyllning

Fräs vitlök och ingefära någon minut. Tillsätt svamp, vitkål och lök och stek på hög värme tills allt mjuknat.

Vispa upp äggen med en gaffel och rör till en krämig äggröra i en panna med lite olja på svag värme.

Blanda ner äggröran, soja och sesamolja i svamp- och kålblandningen. Lägg över i en bunke och låt svalna något.

== Dippsås

Blanda ihop majonnäs, soja, risvinäger, socker och sriracha. Ställ åt sidan.

== Vik dumplings

Lägg ut några plattor på torrt underlag och klicka ca 2 tsk fyllning på varje. Pensla kanterna med lite vatten, vik ihop och tryck till. Håll de färdiga under en fuktig kökshandduk medan du viker resten.

== Ånga

Ånga i 3-4 minuter i en ångkorg med lock. Ett plattare durkslag över en kastrull funkar också – se bara till att dumplingsen inte rör vid varandra.

== Servera

Servera med dippsåsen och strö över salladslök, koriander och sesamfrön.