= Kimchi

== Ingredienser

|===
| 1   | kg         | salladskål
| 2   | msk        | salt
| 1,5 | dl         | vatten
| 2   | msk        | rismjöl
| 1   | msk        | strösocker
| 1   | msk        | riven färsk ingefära
| 2   | klyfta(or) | vitlök
| 0,5 | dl         | fisksås
| 1   | msk        | chiliflakes
| 2   | msk        | paprikapulver
| 2   | st         | morot
| 150 | g          | rättika
|=== 

topping:
sesamfrön

== Tillagning

=== Marinera i Salt

Dela salladskålen i mindre bitar och lägg i en stor skål med vatten. Häll ned salt och blanda noggrant låt sedan stå ca 1 tim. Skölj sedan salladskålen noga.

=== Marinaden

Koka vatten och blanda ned rismjöl och socker under omrörning. Låt svalna något och rör ned fisksås, ingefära, vitlök, chiliflakes och paprikapulver.

=== Hacka grönsaker

Skär resten av grönsakerna i tunna strimlor, tillsätt dem och den saltade salladskålen till chiliblandningen och blanda noggrant.

=== Lagra 

Lägg ned grönsaksblandningen i rena glasburkar, täck med plastfolie och sätt på lock. Fyll inte burkarna helt. Låt stå framme i rumstemperatur 2 dagar.

=== In i kylen

Kimchin ska bubbla av jäsning. Efter de två dagarna förvara kimchin i kylen, servera den efter att den stått i en vecka.

=== Servera

Vid servering toppa kimchin med sesamfrön.
