
= Raggmunkar med fejkon

Serveras med rårörda lingon

== Raggmunkar

|===
| 800 | g   | fast potatis
| 2,5 | dl  | vetemjöl
| 4   | dl  | Mjölk
| 2   | st  | Ägg
| 1   | tsk | salt
|===

* Värm upp ugnen till 125 grader
* Vispa mjölet med hälften av mjölken till en slät smet i en bunke. Vispa ner resten av mjölken, äggen och saltet.
* Skala och riv potatisen grovt. Krama ur vätskan och vänd ner den i smeten genast så att den inte mörknar.
* Hetta upp lite av matfettet i en stekpanna och klicka ner smeten och stek raggmunkarna i omgångar. Håll dem varma på plåten i ugnen.
* Håll varma i ugnen

== Fejkon

|===
| 2 | paket | rökt tofu á 140 g eller 1 paket marinerad tofu á 400 g
| 2 | msk   | ljus soja
| 2 | tsk   | liquid smoke
| 1 | tsk   | agavesirap eller socker
| 2 | msk   | rapsolja
|===


* Om din tofu är vattnig lägger du den press inslagen i hushållspapper i 30 min innan du ska marinera den. Om du pressar ut överflödig vätska suger tofun åt sig bättre av marinaden
* Skriva sedan tofun i tunna skivor och lägg i en plastpåse med övriga ingredienser till marinaden
* Låt marinera så länge du hinner, men minst 30 min
* Stjälp därefter ner hela rasket i en upphettad stekpanna, både tofu och marinad och låt steka på medelvärme tills all marinad absorberats av tofun och tofun blivit knaprig och fått rejält med färg
