= Majs, bön och jalapeño-fritters med coleslaw och tortillabröd

== Coleslaw

|===
| 200 | g   | rödkål
| 1   | st  | äpple
| 2   | st  | morötter
| 1   | tsk | dijonsenap
| 0.5 | dl  | créme/havre fraiche eller majonäs
|     |     | Salt & peppar
|===

Riv äpple och morot grovt. 
Riv eller finhacka rödkålen. 
Blanda ihop dijonsenap och créme fraiche i en bunke, smaka av med salt och peppar. 
Lägg ner de rivna grönsakerna i bunken och rör om så att allt bli täckt av såsen. Ställ åt sidan.

== Fritters

|===
| 3 | dl  | vita bönor, kokta alternativt 1.2 dl torkade vita bönor som du själv blötlägger och kokar i förväg
| 4 | dl  | majs, fryst
| 1 | dl  | ströbröd
| 2 | msk | inlagd jalapeno
| 1 | dl  | riven ost
|===

Mosa eller mixa de kokta vita bönorna och hälften av majsen. 
Grovhacka jalapeno och riv osten. Blanda ihop bön och majsmoset med jalapeno, osten, resterande majs och hälften av ströbrödet. 
Forma till biffar och vänd i resterande ströbröd innan du lägger dem i en panna på medelvärme. 
Stek i en skvätt olja tills biffarna fått färg på båda sidor.

== Tortillabröd

|===
| 4   | dl  | vetemjöl
| 0.5 | tsk | bakpulver
| 0.5 | tsk | salt
| 0.5 | msk | raps-eller olivolja
| 1   | dl  | vatten
|===

Blanda ihop de torra ingredienserna och tillsätt sedan vatten och olja. 
Knåda degen och dela sedan i 4-6 delar. 
Kavla ut varje deg till en rund platt kaka och stek sedan hastigt på hög värme i en stekpanna. 
För att hålla värmen och mjukhet i bröden kan du lägga dem i en handduk.

