Zutaten für 6 Personen:
= Ärtpasta

500g griechischer Joghurt
150ml Olivenöl
4 Knoblauchzehen (zerdrückt oder ganz klein geschnitten)
500g Erbsen (TK, aufgetaut und vorbereitet)
500g Conchiglie (große Muschelnudeln)
60g Pinienkerne
1-2 TL Chiliflocken (je nach gewünschter Schärfe)
40g frisches Basilikum, Blätter zerrissen
250g Feta (am Besten ganz cremiger vom Gemüsehändler)
Salz & Pfeffer, frisch gemahlen
Zubereitung:

Joghurt mit zwei Dritteln des Olivenöls und 100g der Erbsen und dem Knoblauch pürieren, bzw. zu einer cremigen Masse verrühren). Die Joghurtsauce in einer großen Schale bereitstellen.
Die Nudeln parallel in reichlich Salzwasser kochen.
Nun das restliche Öl mit den Pinienkernen und den Chiliflocken in der Pfanne rösten bis sie goldbraun sind und die Flüssigkeit rötlich gefärbt ist.
Die restlichen Erbsen erhitzen.
Die Nudeln abgießen und Stück für Stück mit der Joghurtsauce in der großen Schale vermischen (nicht zu viel auf einmal, sonst gerinnt der Joghurt).
Das Ganze mit ordentlich Pfeffer & Salz abschmecken.
Die Mischung auf dem Teller anrichten, Erbsen drübergeben und Feta darauf zerbröseln. Nun Basilikum darauf streuen und die Pinienkerne mit Öl drübergeben.
