= Fisksoppa

== Hacka grönsaker

|===
| 1    | gul   | lök
| 1    | msk   | olivolja
| 4    | st    | morötter
| 4    | st    | potatisar
|===
Skala och hacka lök, potatis och morötter i småbitar.

== Fräs lök och rotfrukter


Hetta upp en kastrull och fräs rotfrukter + lök en liten stund 

== häll ner tomatpure, dill, fond och vatten. 

|===
| 4    | msk   | hummerfond
| 1    | msk   | tomatpure
| 7    | dl    | vatten
| 1    | kruka | dill
|===


Låt sjuda upp till potatisen är mjuk. 


== Vänd i tomater och lax

|===
| 10   | ST    | körsbärstomater
| 300  | gram  | torsk & lax
|===

Vänd då i tomaterna & Skär lagom små bitar av torsken och vänd ner, låt sjuda i 5- 7 minunter eller tills fisken är genomkokt. 


== Smaka av

Och smaka av med lite salt, fiskkrydda och lite cayenne. 

|===
|      |       | salt  
| lite |       | cayenne
|===

== Runda av med grädde

Runda av med vispgrädde & låt sjuda upp. Ta bort från spisen och vänd i kräftstjärtarna.

|===
| 2    | dl    | vispgrädde
| 140  | gram  | kräftstjärtar
|===