= Lax med hoisinsås 

== Ingredienser

=== Lax

|===
| 500 | g   | lax
| 1   | dl  | hoisinsås
| 2   | msk | ljus soja
| 1   | tsk | gochuang chillipasta elle 1/2 finhackad röd chili
| 1   | tsk | finhackad färsk ingefära
| 1   | st  | finhackad vitlöksklyfta
| 2   | msk | neutral olja
|===

=== Sallad

|===
| 1/2 | st | gurka
| 1   | st | morot
| 100 | g  | rättika
| 2   | st | salladsblad
| 100 | g  | glasnudlar
| 125 | g  | socker ärtor
|===

=== Dressing 

|===
| 1 | st  | Lime
| 2 | msk | sweet chillisås
| 2 | msk | Japansk soya
| 1 | msk | sesamolja
| 2 | msk | finhackad färsk koriander
|===

== Tillagning 

Skär loss laxen från skinner och skör i mindre bitar. Blanda i en skål hoisinsås, soja, gochujang chillipasta (aller finhackad chilli) med finhackad ingefära , vitlök, limesft och skal.

Skala gurkan och hyvla i tunna skivor med en potatisskalare. Skala moorot och rättika och hyvla i tunna skivor med ett juliennjärn eller strimla fint på längden. Skär salladslöken i tunna skivor.

Koake udlarna enligt anvisningarna på förpackningen och låt dem rinna avi ett durkslag. 

Lägg upp alla grönsaker i högar var för sig på ett fat, tillsammans med nudlarna. 

Blanda till dressingen och häll upp i en skål-

Hetta upp en stekpanna, tillsätt oljan och stek laxen ett par minuter på varje sida, tillsätt såsen och vänd runt laxbitarna. 

Lägg upp laxen på fatet och häll över såsen. Dekorera med sesamfrön och koriander. Servera dressingen vid sidan av för att smaksätta grönsakerna med den.

