= Nattjästa surdegsfrallor

== Mata surdegen

|===
| 1   | klick | vetesurdeg
| 150 | g     | vetemjöl
| 150 | g     | vatten
|===

På morgonen: Mata en vetesurdeg så att du har 300 gram bubblande surdeg till kvällen (alltså en klick surdegsgrund, 150 g vetemjöl och 150 g vatten).

== Blanda degen

|===
| 550   | g | vatten, 
| 850   | g | vetemjöl special
| 20–25 | g | salt
|===

På kvällen: Blanda surdegen med 550 g vatten, 850 g vetemjöl (gärna special) och 20–25 g salt. Rör bara ihop tills degen blandats, inte knåda alltså.

== Vik degen
En stund senare (allt mellan 10 och 60 minuter): Vik degen där den ligger i bunken ett varv. Ta tag i degens kanter och vik dem  mot mitten. Täck bunken med lock eller plastfolie och gå och lägg dig (degen får stå i rumstemperatur).

== Forma
På morgonen: Sätt ugnen på 270 grader, skrapa ut degen på ett mjölat bakbord och vik ihop den till ett paket. Inte så noga exakt hur det går till, bara du spänner degen lite. Lägg på en handduk och låt vika tills ugnen är riktigt varm, 40–60 minuter.

Jag gjorde frallor av halva degen genom att bara dela dem i lagom stora bitar med en degskrapa. 

== Grädda 
Skjuts in i ugnen! Andra halvan fick vila medan frallorna bakades av, sen fick den bli en limpa.

== Kommentar

När man gör såna här nattjästa degar på vanlig jäst spelar det ingen roll om degen blir lite överjäst, alltså jäser tills den börjar sjunka ihop. När man bakar med surdeg brukar det dock kunna leda till att degen blir alltför sur och tappar kraft att resa sig i ugnen.
