= Knådfritt vetebröd

1 jättestort bröd, eller två lite mindre

== Surdeg

|===
| Mägnd | Enhet | Ingrediens
| 25    | g     | rågsurdegsgrund
| 100   | g     | vatten
| 55    | g     | rågmjöl
|===

Blanda ihop, täck med lock eller plastfolie och låt stå i rumstemperatur tills surdegen bubblat igång, 6–10 timmar.

== Deg

|===
| Mägnd | Enhet | Ingrediens
| 155   | g     | rågsurdeg
| 500   | g     | vatten
| 750   | g     | vetemjöl special 
| 15–20 | g     | salt
|===

Blanda därefter samtliga ingredienser i en bunke som rymmer minst 4l.
Täck med lock eller plastfolie och låt stå 6–8 timmar.

== Vik

Skrapa ut degen på en rikligt mjölad handduk. 
Vik in kanterna mot mitten och rulla ihop degen så att skarven kommer nedåt. 
Det är inte så noga hur det går till eller hur det ser ut. 

== Jäs

Låt jäsa 1–2 timmar i rumstemperatur.

== Starta ugnen 

Sätt ugnen på 250 grader i god tid, minst 30 minuter före gräddning.

== Ner i grytan 

Vänd över degen i en gryta så att skarven hamnar uppåt, sätt på locket och ställ in grytan på ett galler en bit ned i ugnen. Sätt en klocka på 30 minuter.

== Ta av locket

Ta av locket från grytan och grädda brödet ytterligare 30 minuter.

== Ut ur ugnen

Ta ut grytan och vänd ur brödet. Låt svalna på ett galler.