= Rågböd med hela rågkorn

== Surdegen

|===
| Mägnd | Enhet | Ingrediens
| 30    | g     | Rågsurdegsgrund
| 200   | g     | Ljummet vatten
| 120   | g     | Rågmjöl
|===

Rör ihop surdegsgrund, mjöl och vatten i en rymlig bunke. 
Täck med lock eller plastfolie och låt stå under natten, 8–10 timmar, gärna lite varmt.

== Skållning

|===
| Mägnd | Enhet | Ingrediens
| 500   | g     | vatten
| 150   | g     | rågkärnor
|===

Lägg rågkärnorna i en kastrull, häll på vattnet och koka upp. 
Låt puttra i cirka 20 minuter. 

== Frön

|===
| Mägnd | Enhet | Ingrediens
| 100   | g     | solroskärnor
| 25    | g     | linfrö
| 25    | g     | sesamfrö
| 15    | g     | salt
|=== 

Dra av kastrullen från plattan, häll ner frön och salt, lägg på locket och låt stå över natten.

== Degen

|===
| Mägnd   | Enhet | Ingrediens
|         |       | surdegen och skållningen från gårdagen
| 300     | g     |rågmjöl
| 100     | g     |vetemjöl
| 50      | g     |brödsirap (eller mörk sirap)
| 100–175 | g     |vatten
|===

Blanda surdeg och skållning med de nya ingredienserna. Börja med lite vatten och tillsätt mer tills degen känns lagom. 
Den ska vara ganska lätt och lös, men absolut inte rinnig i konsistensen. 
Hur mycket vatten som går åt beror på hur mycket som gått upp i skållningen och vilken typ av rågmjöl man använder. 
Ett grövre mjöl tar upp mer vatten.

== Lägg i form

Smöra en stor eller två små brödformar och klicka i degen. 
Jag tycker det går enklast med blöt hand. 
Platta till degen, täck formarna med plastfolie och låt jäsa tills de rest sig några centimeter. 
De ska liksom börja se lite trötta ut, inte så spända. Mina fick jäsa ungefär 3 timmar i kylskåp plus 2 timmar i rumstemperatur.

== Starta ugnen

När man känner på sig att ungefär en timmes jäsning återstår sätter man ugnen på 250 grader. 

== Grädda

Och när den blivit riktigt varm och bröden jäst klart strör man på lite frön och lite mjöl om man vill och sen skjuts in i ugnen! 
Sänk temperaturen till 200 grader och låt stå inne i cirka 50 minuter. 
Man kan kolla inntertemperaturen innan man tar ut dem, de bör ha passerat 98 grader för att vara klara.

De sista 10 minuterna kan man vända ur bröden ur formarna och låta dem stå direkt på ett galler eller en baksten, på så vis kan de få lite extra stadga och god skorpa.

== Svalna 

Låt bröden svalna på ett galler och vira sedan in dem i handdukar. 

Om jag skulle ändra något till nästa gång så tar jag nog lite mer linfrö och sesamfrö, de är ju så goda att de kan vara fler.

