= Blomkålsgryta 

Serveras med Ris

== Kryddblandning

|===
| 1   | tsk | lökpulver
| 0,5 | tsk | rökt paprikapulver
| 0,5 | tsk | spiskummin
| 0,5 | tsk | malen koriander
|===

Blanda lökpulver, rökt paprikapulver, spiskummin, malen koriander i en skål.

== Hacka 

|===
| 800 | g  | blomkål
| 1   | st | gul lök
| 2   | st | vitlöksklyftor
| 1   | st | grön paprika
| 1   | st | grön eller röd chilifrukt
| 2   | st | morötter
|===

Skär blomkålen till mindre träd – gör gärna lite varierande storlekar. 
Skär även rotstocken till bitar. 
Halvera den gula löken, skär ett snitt in på varje halva och skiva den (så du får kvartsskivor). 
Hacka vitlöken. 
Kärna ur och strimla paprikan på längden till smala strimlor. '
Skiva chilin och riv morötterna på de stora hålen på ett rivjärn.

== Stek blomkål

Ringla olja i en vid gryta eller traktörpanna och ha ner blomkålen. 
Stek under omrörning på ganska hög värme. 
Strössla över kryddblandningen efter cirka 5 minuter. 
Salta och peppra några varv och stek ytterligare cirka 5 minuter. 
När blomkålen börjat mjukna och få lite yta, lägg ur dem i en skål.

== Stek grönsaker

Ringla lite olja i pannan och ha ner löken. 
Låt den mjukna i några minuter och ha sedan ner vitlöken. 
Ha ner paprika, chili och rivna morötter och låt det stekas några minuter.

== I med vätska

|===
| 5   | dl  | grädde
| 0,5 | tsk | malen ingefära
|     |     | salt, peppar
|===


Slå på grädde och rör i ingefära. 
Smaka av med salt och peppar. 

== I med blomkålen

Låt det puttra ihop i 5 minuter, ös sedan tillbaka blomkålen i pannan. 
Låt det puttra 2 minuter till och servera sedan med kokt ris.