= Mapu Tofu

https://yipin.se/recept/mapo-tofu/[YIPIN] 

https://www.koket.se/vegetarisk-mapo-tofu[Jennie Wallden]


* Svamp
* Färs 
* Ingefära

|===
| Mägnd | Enhet | Ingrediens
| 400   | g     | Naturell fast tofu
|   1   | tsk   | sichauanpeppar
|       |       | neutral olja
|   3   | st    | vitlöksklyftor
|   1   | msk   | riven ingefära
|   1   | msk   | sambal olek
|   3   | msk   | japansk soya
|   1   | tsk   | Sesam-olja 
| 200   | g     | valfri färs
|   2   | tsk   | misopasta
|   2   | msk   | vitt vin
| 4-5   | dl    | vatten 
|   2   | msk   | socker 
|   1   | msk   | majsstärkelse utblandat med 1 msk vatten
|===

== Rosta peppar

Hetta upp en stor stek- eller wokpanna, häll ned sichuanpeppar och rosta i någon minut. Häll sedan upp pepparn i en mortel och mortla finkornigt.

== Kryddor och färs

Häll i olja i pannan och fräs riven vitlök, riven ingefära, sambal oelek, sesamolja och sojasås. Tillsätt färs och stek hårt.

== Koka
Addera misopasta och sedan vinet. Koka på låg värme en stund. 

== Tärna tofu

Under tiden, tärna tofun i ca 1 ½ cm stora kuber och koka ris enligt instruktioner på förpackningen.

== Blanda och koka

Häll över vatten, socker, tärnad tofu och sichuanpepparn i pannan. Koka i ca 10–15 minuter. 

== Majssträkelse

Blanda sedan ut majsstärkelse i lite vatten och blanda i pannan. Låt koka några minuter tills önskad konsistens.

== Servera 

Servera med kokt ris och toppa med hackad salladslök och koriander. Njut av din smarriga mapo tofu!
