= Baguette

== Ingredienser

|===
| 400 | g | Vatten
| 250 | g | Vete surdeg
| 600 | g | Vetemjöl Special
| 10  | g | Ljus Sirap
| 30  | g | Salt
|===

== Blanda

Bland samliga ingredienser utom saltet 

Kör degen på melnaväxeln 6 minuter eller knåda i 10 minuter

Tillsätt saltet 

Kör degen på mellanväxeln 8 minuter eller knåda i 15 minuter

== Vila 

Låt degen vila i 2 timmar

== Dela

Dela degen i 4 delar

== Forma

Vik ihop och rulla ut till spetsiga baguetter

Lägg en kökshanduk på en plåt och stö över vetemjöl

Lägg baguetten på den mjölade hadduken med verket uppåt.

Forma handduken så att bauetterna hamnar i handdukens "dalar"

== Jäs

Strö lite mjöl över baguetterna och lägg sedan en hadduk över dem

Låt dem stå svalt (16-18 grader) och jäsa i 10-15 timmar.

== Grädda

Sätt ugnen på 250 grader 

Ta bort handuken ovanpå baguetterna och lägg bakpapper på en plåt.

Vänd på baguetterna och ta bort den handduken som baguetterna legat på.

Skär fem sneda snitt på ovansidan.

Sänk värmen till 230 grader och låt baguetterna stå inne i 20-30 minuter.De ska bakas hårt.

