= Kalljäst Levain

https://vardagsgladje.ballingslov.se/surdegsbrod-kalljast-levain-ett-recept-av-daniel-larsson/?fbclid=IwAR3NwR_5bimpcgL2E1QLEt-WsmvT1RC7qow-Oce98JC1myWiH5FWa_N-YmE#:~:text=Blanda%20mj%C3%B6l%20och%20vatten%20f%C3%B6r,att%20komma%20ig%C3%A5ng%20med%20j%C3%A4sningen[Källa]



=== Ingredienser

|===
| 700 | g | Ekologisk vetemjöl special
| 100 | g | Ekologiskt fullkornsvete av kulturspannmål (t.ex Dinkel)
| 575 | g | vatten
| 20  | g | salt (eller 25g havssalt)
| 200 | g | surdeg
|===

== Steg 1 (12h)

Förbered 200g surdeg så den är mogen till dess att degen ska blandas. Min rekommendation är att du dagarna innan följer denna rutin: Spill ut och skrapa ur nästan allting från burken, låt endast skrapet på botten och väggarna vara kvar. Fyll på med lika delar vatten och mjöl (en blandning med minst en fjärdedel ekologiskt fullkornsvete eller råg). 50g av båda duger. Upprepa morgon och kväll och låt burken stå framme i rumstemperatur mellan ”matningarna”. Sista matningen innan du ska använda surdegen i grunden fyller du på med 100g vatten och 100g mjöl. Du kan med fördel göra detta på kvällen innan läggdags så har du en mogen surdeg av rätt mängd på morgonen dagen efter.

== Steg 2 (2h)

Blanda mjöl och vatten för hand i en bunke (5l) för en så kallad ”autolys” där gluten börjar bildas utan att du behöver knåda. Låt stå 30 minuter, upp till två timmar. Vattnet kan med fördel vara kring 27 grader, eller varmare än fingret, kallare än handleden. Detta hjälper degen att komma igång med jäsningen.

== Steg 3 (10 min)

Blanda i den mogna surdegen och saltet. Kläm in allting ordentligt och knåda för hand i bunken, eller på lägsta hastighet i köksassistent i 5-10 minuter. Placera sedan degen i en ren skål. Om du vill kan du även olja den väldigt lätt med en neutral olja, t.ex rapsolja.

== Steg 4 (3.5h)

Efter 30 minuter viker du degen i bunken genom att lyfta och dra upp sidorna över mitten. Första vikningen går du två varv i bunken. Upprepa sedan vikningen varje halvtimme till timme under de kommande 3,5 timmarna (ett varv i bunken räcker för dessa). Den sista timmen låter du degen vila utan vikningar. Degen ska ha rest sig ca 50% från sin ursprungsvolym. Har den inte gjort detta så väntar du ytterligare.

== Steg 5

Vänd upp degen på ett lätt mjölat bord och dela i två bitar. Forma lätt till två runda bitar.

== Steg 6

Vänta 20 minuter. Mjöla bordet igen och ovanpå degbitarna. Vänd dem upp och ned på den mjölade ytan och forma till limpor genom att skapa lager på lager och trycka till (se videon). Mjöla toppen på degen och lägg ned med sömmen uppåt i en jäskorg som du klätt med en kökshandduk. Det går också att lägga i durkslag med en kökshandduk. Det är viktigt att degen får andas när den ska jäsa upp igen. Lägger du den i en tät skål kommer det bildas kondens.

== Steg 7 (14-24h)

Ställ degarna i kylen och täck med en kökshandduk. Här får de nu stå i 14-24 timmar.

== Steg 8

En timme innan du vill baka startar du ugnen på 220C med extra undervärme eller 240C på över/under-värme. Har du en baksten eller ett bakstål ställer du in det på ett galler, nästan längst ned i ugnen och låter denna förvärmas med ugnen. Placera också en ugnsplåt som du inte är så rädd om längst ned i ugnen. Det går också att baka på vanlig ugnsplåt, men botten kan bli lite bränd. När det är dags att baka vänder du ut degen från jäskorgen på en pizzaspade eller skärbräda i trä, med en bit bakplåtspapper mellan. Mjöla toppen på degen och skär ett eller flera snitt i degen med ett rakblad eller vass sågtandad kniv. Ju tunnare kniv desto bättre! De längre snitten bör vara ca 5mm djupa. Skjutsa in degen på stålet/stenen/plåten och kasta in ca 2dl vatten på plåten längst ned. Stäng därefter ugnen. Har du en ångfunktion startar du denna så att luften hålls kontinuerligt fuktig under baket. Har du inte detta kan du rulla ihop några kökshanddukar du inte är rädd om i en gammal brödform, ställa den på plåten längst ned och fylla den till hälften med kokande vatten, ca 10 minuter innan bakning.

Efter 20 minuter öppnar du ugnen och sänker temperaturen 10 grader. Rotera brödet om det har ojämn färg och baka ytterligare 10-15 minuter till önskad färg på skorpan. Låt svalna på ett galler en timme innan du skär i det! Skär skivor från mitten och ställ brödet med snitten nedåt på en skärbräda, med en kökshandduk som täcke.

