= Segt, håligt och väldigt gott

http://paindemartin.blogspot.com/2009/04/segt-haligt-och-valdigt-gott.html?m=1[Källa]

Två stora bröd

== Dag 1, kväll

|===
| Mägnd | Enhet | Ingrediens
| 100   | g     |vetesurdegsgrund
| 200   | g     |ljummet vatten
| 150   | g     |vetemjöl special
| 50    | g     |rågmjöl
|===


Blanda surdegsgrund, vatten och mjöl i en rymlig bunke, täck med plast och ställ lite lagom varmt under natten.
Jag ställer den som alltid i skåpet ovanför kylskåpet, där det är någonstans me llan 22 och 24°.

== Dag 2, morgon
  
|===
| Mägnd | Enhet | Ingrediens
3+| Surdegen från gårdagen
| 450   | g     | vatten
| 750   | g     | vetemjöl special
| 20    | g     | salt
|===

Blanda alla ingredienser utom saltet.
Kör 8 minuter i degblandare (5 minuter på låg hastighet och 3 minuter med lite mer fart). 
Tillsätt saltet. 
Kör ytterligare 2 minuter. 

Degen ska ha bra spänst och bör släppa en aning från bunkens kanter.
Den ska vara aningen klibbig utan att kleta fast på fingrarna om man tar i den. 
Känns den inte klar, låt vila 5 minuter och kör sedan några minuter till.

== Jäsning

Smörj en plastlåda med raps- eller annan neutral olja.
Lägg över degen i lådan och sätt på locket. 
Markera gärna på lådan var degen befinner sig, så har du koll på hur den jäser. 

== Vik

Degen jäsa tills den uppnått dubbel storlek, vilket kan ta 3–5 timmar. 
Under tiden den jäser viker du ihop degen tre gånger där den ligger i lådan. 
Första gången efter 1 timme, därefter med 30 minuters mellanrum. 
Med blöta händer viker du degen från vänster in mot mitten, och från höger mot mitten, uppifrån och nerifrån. 
Det är inte så noga hur det går till, bara man känner att degen spänns.

== Värm ugnen

Sätt ugnen på 275 grader i god tid. 
Placera en plåt eller baksten i mitten av ugnen och en oöm plåt på nedersta hyllan.

== Forma

Vänd upp degen på ett mjölat bakbord och dela den i två delar. 
Utan att trycka ut luften ur degen, dra ut en av bitarna till en cirka 30 x 30 centimeter stor kvadrat. 
Strö lite mjöl längs sidorna och vik ihop den en gång till ett avlångt bröd. 
Låt skarven vara på sidan så kan brödet spricka där om det vill. 
Lyft försiktigt över degen till ett bakplåtspapper.

== Grädda

Sätt in brödet i ugnen och lägg några isbitar på den undre plåten. 
Sänk genast temperaturen till 250 grader. 
Efter 15 minuter sänker du till 200 grader och vädrar ugnen genom att öppna och stänga luckan. 

Upprepa vädringen ungefär var 5:e minut tills brödet är färdigt. 
Ta ut brödet efter totalt 30–35 minuter (innertemperatur cirka 96 grader). 
Ta ut bröden och låt svalna på ett galler.