= Hantera en surdeg


Surdegen behöver matas med jämna mellanrum

Det sägs att man ska mata den två gånger per dag om man ska ha en stark och livlig surdeg att baka med. 

Det låter tidskrävande och alldeles för jobbigt tycker jag.

Jag matar surdegen 1 gång i veckan och förvarar den i kylen mellan matningarna. Ibland kan det gå mer tid mellan matningarna också. Upp till 3 veckor kan den överleva i kylen.

När jag matat surdegen låter jag den stå över natten i rumstemperatur innan jag stäler in den i kylen.

Vet jag att jag ska baka till helgen tar jag ut surdegen några dagar innan och matar den en gång per dag utan att ställa in den i kylen emellan. Oftast glömmer jag det och det går lika bra det. Att mata den en gång innan man börjar på degen kan vara bra men inte nödvändigt.

Jag har ca 100 g surdeg stående i en burk för jämnan när jag matar den tar jag ur allt utom ca 30 g och sedan fyller jag på med ca 50 g vatten  och drygt 40 g vetemjöl varje gång.

När det står i recept att man ska ha 200 g surdeg till baket. Är det bara att ta ca 30 g surdeg ur sin surdegsburk till en ny bunke eller burk tillsätter lika mängd mjöl och vatten så det blir 200 g totalt. Sedan fortsätter jag mata den ursprungliga surdegen i den ursprungliga burken.
