= Syrligt Lant bröd

== Fördegen

|===
| 150  | g | Rågsurdegsgrund
| 425  | g | Ljummet vatten
| 300  | g | Vetemjöl Special
| 150  | g | Rågmjöl
|===

Bland aalla ingredienser i en rymlig bunke.
Låt stå på ett varmt ställe över natten.

== Degen

|===
| 200  | g | Vatten
| 500  | g | Vetemjöl Special
| 20   | g | Salt
|===

Blanda samman fördegen och de nya ingredienserna utom saltet i bunken.

Kör 8 minuter i degblandaren (5 minuter låg hastighete och 3 minuter lite snabbare)

Tillsätt saltet.

Kör ytterligare 2 minuter.

== Jäsning

Smörj en plastlåda red neutral olja.
Låt degen jäsa tills den uppnått dubbel storlek. (3-5 timmar)

När degen jäser viker du den tre gånger där den ligger i lådan. Första gången efter en timma och sedan med 30 minuters mellanrum.

== Grädda

Sätt ugnen på 275 C.

Mjöla tre jäskorgar.

Dela degen i tre delan och lägg försiktigt en i varje korg

Låt jäsa ytterligare 30 minuter

Sätt in bröden i mitten av ugnen och placera lite vatten på bottenplåten i ugnen. Sänk temperaturen till 250 grader C.

Efter 15 minuter sänk temperaturen till 180 grader C

När bröden stått inne i ca 35-40 minuter är de klara (innertemperatur 98 grader)

Låt svalna å ett galler.

