= Vörtbröd


== Instruktioner

=== DAG 1, MORGON
|===
| 165 | g  | vatten
| 80  | g  | fint rågmjöl
| 5   | dl | svagdricka, porter eller julmust
|===

* Koka upp vattnet och häll det över mjölet, rör runt och täck bunken med lock. Låt stå i rumstemperatur till eftermiddagen.
* Reducera ner 5 dl svagdricka, porter eller julmust till 1 dl. Ställ vörten sedan i kylen. Detta blir en slags låtsasvört.
* Mata din surdeg så den är pigg till eftermiddagen.

=== DAG 1, SEN EFTERMIDDAG

|===
| 130     | g  | surdeg
|         |    | skållningen från morgonen
| 25      | g  | honung
| 65      | g  | flytande vört
| 100-200 | g  | vatten
| 25      | g  | mörk sirap
| 2       | g  | mald nejlika (ca 2 krm)
| 2       | g  | mald pomerans (ca 2 krm)
| 2       | g  | mald ingefära (ca 2 krm)
| 8       | g  | havssalt
| 340     | g  | vetemjöl
| 33      | g  | blötlagda och avrunna russin
|===

* Gör en hög av mjölet på bakbordet och forma sedan ett hål i mjölet där du kan hälla övriga ingredienser utom russinen.
* Arbeta in mjölet lite i taget. Vattenmängden justerar du medan du jobbar in mjölet så degen får en bra konsistens, degen ska vara lite * klistrig. Lägg degen i en bunke och låt den vila 1 h.
* Vik degen och låt den vila 1 h till. Upprepa vila-vikastegen 4-5 gånger. Vid sista vikningen tillsätter du russinen.
* Forma brödet till en limpa och lägg i jäskorg med handduk. Lägg dubbla handdukar över och låt brödet jäsa i rumstemperatur till morgonen.

=== DAG 2, MORGON

* Sätt ugnen på 250 °C.
* Pensla brödet med uppvispat ägg.
* Ställ in brödet och sänk temperaturen till 180 °C. Grädda brödet tills innertemperaturen är 98 °C.
* Pensla brödet med smält smör när du tar ut det ur ugnen.