= Silltårta

== Ingredienser
|===
3+|smör
|2     | förp | hönökaka
|5     | dl   | västerbottenost
|1     | dl   | gul lök (finhackad)
|3     | dl   | gräddfil
|6     | st   | hårdkokta ägg
|1-2   | krm  | nymald vit/svart-peppar
|2     | dl   | majonäs
|2-3   | dl   | mycket finstrimlad grönsallad
|600   | g    | löksill
|260   | g    | senapsill
|275   | g    | tomatsill
|1-1.5 | dl   | finhackad gräslök
3+|lökringar av rödlök
|===

== Smöra
Smöra samtliga bröd på ena sidan. 
Lägg två av bröden på ett stort uppläggningsfat eller bricka så att de bildar en rind botten

== Smet lager
Fördela och bred ut den rivna osten över botten samt strö över den hackade gula löken. Bred ut gräddfilen över osten.

== Ägg lager
Lägg på nya bröd och se till att skarven kommer med en förskjutning gentemot den nedre skarven. 
Täck dessa bröd med skivade hårdkokta ägg. 
Krydda äggskivorna med nymald peppar samt bred ut majonäsen.

== Sallads lager
Lägg på de två sists bröden och täck dessa med ett tunt lager mycket finstrimlad grönsallad. 

== Sillen
Skär den inlagda sillfilen i lagom bitar och lägg dem som en uttre ring å tårtan.
Fortsätt med en mellanlager av senapssill och slutligen tomatsillen i mitten. 

== Garnera
Garnera silltårtan med finhackad gräslök, löringar av rödlök eller gul lök ssamt små dillvippor.